- hosts: docker
  become: yes
  tasks:
  - name: Ensure dnf-plugins-core is installed.
    dnf:
      name: dnf-plugins-core
      state: present

  - name: Add docker repository to host.
    command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

  - name: Make sure old versions of docker aren't already installed.
    dnf:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-selinux
        - docker-engine-selinux
        - docker-engine
      state: absent

  - name: Install latest version of docker + accoutrements.
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python-docker-py
        - python-pip
      state: latest

  - name: Copy systemd drop-in to allow for portainer connection.
    copy:
      src: startup_options.conf
      dest: /etc/systemd/system/docker.service.d/startup_options.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: Enable and run docker.service.
    systemd:
      name: docker
      daemon_reload: yes
      masked: no
      enabled: yes
      state: restarted
